---
title: "Figure 3 Heatmaps FAIMS"
author: "Anji"
date: "March 15, 2021"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(root.dir = "G:/Projects/Proteomics/Zymomona")
knitr::opts_chunk$set(root.dir = "G:/Projects/Proteomics/Zymomona/DataAnalysis/", warning = FALSE, message = FALSE)
```

```{r install_packages, echo=FALSE}
library(pcaMethods)
library(ggplot2)
library(pheatmap)
library(plotly)
library(reshape2)
library(RColorBrewer)
library(viridis)
library(plyr)
library(gridExtra)
library(grid)

```

## R Markdown


```{r load_data_FAIMS, echo=FALSE}
ETDIGVTGGGQGK_CompiledFragments_0_6_FAIMS_20ppm <- read.csv("P:/EAT_20190926_Zymomona/Zymo_FAIMS_Parameters/IW_0_6/CompiledFragmentResults_ETDIGVTGGGQGK_IW_0_6_Zymo_FAIMS_20ppm.csv", 
                                        header = TRUE, sep = ",", stringsAsFactors = FALSE)


AIEIVDQALDR_CompiledFragments_0_6_FAIMS_20ppm <- read.csv("P:/EAT_20190926_Zymomona/Zymo_FAIMS_Parameters/IW_0_6/CompiledFragmentResults_AIEIVDQALDR_IW_0_6_Zymo_FAIMS_20ppm.csv", 
                                        header = TRUE, sep = ",", stringsAsFactors = FALSE)

```

```{r load_data_withoutFAIMS, echo=FALSE}
ETDIGVTGGGQGK_CompiledFragments_0_6_noFAIMS_20ppm <- read.csv("P:/EAT_20190926_Zymomona/Zymo_NoFaims_Parameters/IW_0_6/ISPH-ISPG/CompiledFragmentResults_ETDIGVTGGGQGK_IW_0_6_Zymo_20ppm.csv", 
                                         header = TRUE, sep = ",", stringsAsFactors = FALSE)
```


```{r dataformatting_replicates, echo=FALSE}
#x = CompiledFragments_0_6_FAIMS_20ppm
meta_replicates <- function(x){
  samples <- colnames(x[,-c(1:2)])
  samples <- gsub("^.*?_R","R",samples)
  
  df <- x[,-c(1:2)]
  rownames(df) <- x$Mass.Feature
  colnames(df) <- samples
  df[df == 0] <- NA
  
  df <- df[-which(rownames(df)=="b1"),]
  df <- df[-which(rownames(df)=="y1"),]
  
  df_t <- t(df)
  
  meta <- as.data.frame(stringr::str_split_fixed(rownames(df_t),"_",4))
  colnames(meta) <- c("Resolution", "MaxInjection", "AGC", "Replicate")
  
  meta[,1] <- sub('R','', meta[,1])
  
  meta[,2] <- sub('MI', '', meta[,2])
  meta[,2] <- sub(502, 0.502, meta[,2])
  meta[,2] <- as.factor(as.numeric(meta[,2]))
  
  meta[,4] <- sub("*.raw",'', meta[,4])
  meta[,4] <- as.numeric(sub("_2020.*",'', meta[,4]))
  
  rownames(meta) <- rownames(df_t)
  meta <- meta[order(meta[,1],meta[,2]),]
  
  if(length(grep("CORRUPTED",rownames(meta))) != 0){
    meta <- meta[-grep("CORRUPTED",rownames(meta)),]
  }
  
  return(meta)
  
}

# x = CompiledFragments_0_6_FAIMS_20ppm
# m = meta_0_6_FAIMS_20ppm
# m = meta

df_fragments_log2 <- function(x,m){
  samples <- colnames(x[,-c(1:2)])
  samples <- gsub("^.*?_R","R",samples)
  
  df <- x[,-c(1:2)]
  rownames(df) <- x$Mass.Feature
  colnames(df) <- samples
  
  df[df == 0] <- NA
  df <- log2(df)
  df[is.na(df)] <- 0
  
  df <- df[-which(rownames(df)=="b1"),]
  df <- df[-which(rownames(df)=="y1"),]
  
  df <- df[rownames(m)]
  
  return(df)
  
}

replicate_annotation <- function(x,m){
  
  if(length(grep("CORRUPTED", rownames(m))) > 0){
    m <- m[-c(grep("CORRUPTED", rownames(m))),]
  }
  
  
  annotation_res = data.frame(Resolution = m$Resolution)
  rownames(annotation_res) <- colnames(x)
  
  annotation_MI = data.frame(MaxInjection = m$MaxInjection)
  rownames(annotation_MI) <- colnames(x)
  
  annotation = cbind(annotation_res, annotation_MI)
  
  return(annotation)
}

```


```{r dataformatting_unique, echo=FALSE}
# x <- df_0_6_FAIMS_log2_20ppm
# meta <- meta_0_6_FAIMS_20ppm
averagedIntensity <- function(x,meta){
  
  meta$Res_MI <- paste0(meta$Resolution, "_", meta$MaxInjection)
  meta$Raw <- rownames(meta)
  
  
  df_t <- as.data.frame(t(x))
  
  df_t$Raw <- rownames(df_t)
  
  df_t_meta <- merge(meta, df_t, by = "Raw")

  df_t_averaged <- aggregate(df_t_meta[,-c(1:6)], by = list(df_t_meta$Res_MI), mean)
  colnames(df_t_averaged) <- c("Unique", colnames(df_t_averaged[,-1]))
  
  
  meta_unique <- as.data.frame(stringr::str_split_fixed(df_t_averaged$Unique,"_",2))
  colnames(meta_unique) <- c("Resolution", "MaxInjection")
  
  #meta_unique[,1] <- sub('R','', meta_unique[,1])
  
  #meta_unique[,2] <- sub('MI', '', meta_unique[,2])
  meta_unique$Unique <- paste0(meta_unique$Resolution, "_", meta_unique$MaxInjection)
  
  df_averaged_merge <- merge(meta_unique, df_t_averaged, by = "Unique")
  unique_row_names <- paste0("R",meta_unique$Resolution,"_","MI",meta_unique$MaxInjection)
  unique_row_names <- sub("0.502", "502", unique_row_names)
  rownames(df_averaged_merge) <- unique_row_names
  df_averaged_ordered <- t(df_averaged_merge[,-c(1:3)])
  
  return(df_averaged_ordered)

}

#x = annotation_0_6_FAIMS
unique_annotation <- function(x){
  x$sample.names <- sub('_AGC.*', '',rownames(x))
  #x$sample.names <- sub('502', '0.502',rownames(x))
  x <- x[!duplicated(x$sample.names),]
  rownames(x) <- x$sample.names
  
  return(x[,-3])
}
```

```{r log2_replicates_ETDIGVTGGGQGK, echo=FALSE}
ETDIGVTGGGQGK_meta_0_6_FAIMS_20ppm  <- meta_replicates(ETDIGVTGGGQGK_CompiledFragments_0_6_FAIMS_20ppm)
ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm <- df_fragments_log2(ETDIGVTGGGQGK_CompiledFragments_0_6_FAIMS_20ppm, ETDIGVTGGGQGK_meta_0_6_FAIMS_20ppm)

ETDIGVTGGGQGK_annotation_0_6_FAIMS_20ppm <- replicate_annotation(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm, ETDIGVTGGGQGK_meta_0_6_FAIMS_20ppm)


### No FAIMS data
ETDIGVTGGGQGK_meta_0_6  <- meta_replicates(ETDIGVTGGGQGK_CompiledFragments_0_6_noFAIMS_20ppm)
ETDIGVTGGGQGK_df_0_6_log2 <- df_fragments_log2(ETDIGVTGGGQGK_CompiledFragments_0_6_noFAIMS_20ppm, ETDIGVTGGGQGK_meta_0_6)


ETDIGVTGGGQGK_annotation_0_6 <- replicate_annotation(ETDIGVTGGGQGK_df_0_6_log2, ETDIGVTGGGQGK_meta_0_6)
```


```{r log2_replicates_AIEIVDQALDR, echo=FALSE}

AIEIVDQALDR_meta_0_6_FAIMS_20ppm  <- meta_replicates(AIEIVDQALDR_CompiledFragments_0_6_FAIMS_20ppm)
AIEIVDQALDR_df_0_6_FAIMS_log2_20ppm <- df_fragments_log2(AIEIVDQALDR_CompiledFragments_0_6_FAIMS_20ppm, AIEIVDQALDR_meta_0_6_FAIMS_20ppm)

AIEIVDQALDR_annotation_0_6_FAIMS_20ppm <- replicate_annotation(AIEIVDQALDR_df_0_6_FAIMS_log2_20ppm, AIEIVDQALDR_meta_0_6_FAIMS_20ppm)

```

```{r heatmap_prep, echo=FALSE}
theme_set(theme_bw(base_size = 16))

dat <- data.frame(values = as.numeric(as.matrix(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm)))
ggplot(dat, aes(values)) + geom_density(bw = "SJ")

## ----uniform-color-breaks------------------------------------------------
mat_breaks <- seq(min(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm), max(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm), length.out = 10)
cols <- brewer.pal(3, "YlGnBu")
scaleRYG <- colorRampPalette(cols)(length(mat_breaks) - 1)


## ----uniform-color-breaks-detail, fig.height=2, echo=FALSE---------------
dat_colors <- data.frame(
  xmin = mat_breaks[1:(length(mat_breaks)-1)],
  xmax = mat_breaks[2:length(mat_breaks)],
  ymin = 0,
  ymax = max(density(mat, bw = "SJ")$y),
  fill = scaleRYG,#rev(inferno(length(mat_breaks) - 1)),
  stringsAsFactors = FALSE
)
ggplot() +
  geom_rect(
    data = dat_colors,
    mapping = aes(
      xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = fill
    )
  ) +
  geom_density(
    data = dat,
    mapping = aes(values),
    bw = "SJ", color = "cyan"
  ) +
  scale_fill_manual(values = rev(dat_colors$fill))+
  theme(legend.position = "none") +
  labs(title = "Uniform breaks")

## ----uniform-color-breaks-bars, fig.height=3, echo=FALSE-----------------
dat2 <- as.data.frame(table(cut(
  as.matrix(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm), mat_breaks
)))
dat2$fill <- scaleRYG
ggplot() +
  geom_bar(
    data = dat2,
    mapping = aes(x = Var1, weight = Freq, fill = Var1),
    color = "black", size = 0.1
  ) +
  coord_flip() +
  scale_fill_manual(values = dat2$fill) +
  theme(legend.position = "none") +
  labs(y = "data points", x = "breaks",
       title = "Number of data points per color")

```


```{r heatmaps_replicate,echo=FALSE}
pheatmap(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm,
         #annotation = annotation_res,
         annotation_colors = my_colour,
         annotation_col = ETDIGVTGGGQGK_annotation_0_6_FAIMS_20ppm,
         color = scaleRYG,
         #scale = "row",
         breaks = c(0,7,9,11,14,16,18,19, 20,21),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(9,18,27),
         gaps_row = c(1,12),
         show_colnames = F,
         main = "ETDIGVTGGGQGK IW of 0.6 Da with FAIMS 20ppm")

pheatmap(AIEIVDQALDR_df_0_6_FAIMS_log2_20ppm,
         #annotation = annotation_res,
         annotation_colors = my_colour,
         annotation_col = AIEIVDQALDR_annotation_0_6_FAIMS_20ppm,
         color = scaleRYG,
         #scale = "row",
         breaks = c(0,7,9,11,12,14,16,17,18,20),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(9,18,27),
         gaps_row = c(1,12),
         show_colnames = F,
         main = "AIEIVDQALDR IW of 0.6 Da with FAIMS 20ppm")
```

```{r noFAIMS_heatmaps_Replicates, echo=FALSE}

pheatmap(ETDIGVTGGGQGK_df_0_6_log2,
         annotation_colors = my_colour,
         annotation_col = ETDIGVTGGGQGK_annotation_0_6,
         color = scaleRYG,
         breaks = c(0,7,9,11,14,16,18,19, 20,21),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(9,18,27),
         gaps_row = c(11),
         show_colnames = F,
         main = "ETDIGVTGGGQGK IW of 0.6 Da without FAIMS")

```

```{r log2_unique, echo=FALSE}

ETDIGVTGGGQGK_unique_annotation_0_6_FAIMS_20ppm <- unique_annotation(ETDIGVTGGGQGK_annotation_0_6_FAIMS_20ppm)
ETDIGVTGGGQGK_averaged_0_6_FAIMS_log2_20ppm <- averagedIntensity(ETDIGVTGGGQGK_df_0_6_FAIMS_log2_20ppm, ETDIGVTGGGQGK_meta_0_6_FAIMS_20ppm)

AIEIVDQALDR_unique_annotation_0_6_FAIMS_20ppm <- unique_annotation(AIEIVDQALDR_annotation_0_6_FAIMS_20ppm)
AIEIVDQALDR_averaged_0_6_FAIMS_log2_20ppm <- averagedIntensity(AIEIVDQALDR_df_0_6_FAIMS_log2_20ppm, AIEIVDQALDR_meta_0_6_FAIMS_20ppm)

```


```{r heatmap_unique, echo=FALSE}

pdf("F:/Projects/Proteomics/Zymomona/FAIMS/Figures/FromR/Parameter_Comparisono_HeatMaps/20ppm/ETDIGVTGGGQGK_averaged_0_6_FAIMS_log2_20ppm_heatmap.pdf", width = 7, height = 11,useDingbats = FALSE)
pheatmap(ETDIGVTGGGQGK_averaged_0_6_FAIMS_log2_20ppm,
         annotation_colors = my_colour,
         annotation_col = ETDIGVTGGGQGK_unique_annotation_0_6_FAIMS_20ppm,
         color = scaleRYG,
         breaks = c(0,7,9,11,14,16,18,19, 20,21),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(3,6,9),
         gaps_row = c(1,12),
         show_colnames = F,
         width = 7,
         height = 11,
         main = "ETDIGVTGGGQGK IW of 0.6 Da with FAIMS")
dev.off()

pdf("F:/Projects/Proteomics/Zymomona/FAIMS/Figures/FromR/Parameter_Comparisono_HeatMaps/20ppm/AIEIVDQALDR_averaged_0_6_FAIMS_log2_20ppm_heatmap.pdf", width = 7, height = 11,useDingbats = FALSE)
pheatmap(AIEIVDQALDR_averaged_0_6_FAIMS_log2_20ppm,
         annotation_colors = my_colour,
         annotation_col = AIEIVDQALDR_unique_annotation_0_6_FAIMS_20ppm,
         color = scaleRYG,
         breaks = c(0,7,9,11,12,14,16,17,18,20),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(3,6,9),
         gaps_row = c(1,10),
         show_colnames = F,
         width = 7,
         height = 11,
         main = "AIEIVDQALDR IW of 0.6 Da with FAIMS")
dev.off()
```


```{r print_heatmap, echo=FALSE}

E_FAIMS_0_6 <- pheatmap(ETDIGVTGGGQGK_averaged_0_6_FAIMS_log2_20ppm,
         annotation_colors = my_colour,
         annotation_col = ETDIGVTGGGQGK_unique_annotation_0_6_FAIMS_20ppm,
         color = scaleRYG,
         breaks = c(0,7,9,11,14,16,18,19, 20,21),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(3,6,9),
         gaps_row = c(1,12),
         show_colnames = F,
         width = 7,
         height = 11,
         main = "ETDIGVTGGGQGK IW of 0.6 Da with FAIMS")

A_FAIMS_0_6 <- pheatmap(AIEIVDQALDR_averaged_0_6_FAIMS_log2_20ppm,
         annotation_colors = my_colour,
         annotation_col = AIEIVDQALDR_unique_annotation_0_6_FAIMS_20ppm,
         color = scaleRYG,
         breaks = c(0,7,9,11,12,14,16,17,18,20),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         gaps_col =c(3,6,9),
         gaps_row = c(1,10),
         show_colnames = F,
         width = 7,
         height = 11,
         main = "AIEIVDQALDR IW of 0.6 Da with FAIMS")

pdf("F:/Projects/Proteomics/Zymomona/FAIMS/Figures/FromR/Parameter_Comparisono_HeatMaps/20ppm/ETDIGVTGGGQGK_AIEIVDQALDR_averaged_0_6_FAIMS_log2_20ppm_heatmap.pdf", width = 20, height = 15,useDingbats = FALSE)
grid.arrange(grobs = list(E_FAIMS_0_6[[4]],A_FAIMS_0_6[[4]]), ncol = 2)
dev.off()

```





```{r y7y8y9_functions, echo=FALSE}

# x = ETDIGVTGGGQGK_CompiledFragments_0_6_FAIMS_20ppm
# m = ETDIGVTGGGQGK_meta_0_6_FAIMS_20ppm

df_y7y8y9_norm <- function(x){
  samples <- colnames(x[,-c(1:2)])
  samples <- gsub("^.*?_R","R",samples)
  
  df_y7 <- x[grep("y7",x$Mass.Feature),]
  df_y8 <- x[grep("y8",x$Mass.Feature),]
  df_y9 <- x[grep("y9",x$Mass.Feature),]
  
  df_y7_y8_y9 <- rbind(df_y7, df_y8, df_y9)
  df <- df_y7_y8_y9[, -c(1:2)]
  
  colnames(df) <- samples
  rownames(df) <- c("y7", "y8", "y9")
  df<- df[rownames(m)]
  
  t_df <- as.data.frame(t(df))
  t_df$Raw <- rownames(t_df)
  
  meta <- as.data.frame(stringr::str_split_fixed(rownames(t_df),"_",4))
  colnames(meta) <- c("Resolution", "MaxInjection", "AGC", "Replicate")
  
  meta$Resolution <- sub('R','', meta$Resolution)
  
  meta$MaxInjection <- sub('MI', '', meta$MaxInjection)
  meta$MaxInjection <- sub(502, 0.502, meta$MaxInjection)
  meta$MaxInjection <- as.factor(as.numeric(meta$MaxInjection))
  
  meta[,4] <- sub("*.raw",'', meta[,4])
  meta[,4] <- as.numeric(sub("_2020.*",'', meta[,4]))
  meta$Unique <- paste0(meta$Resolution,"_", meta$MaxInjection)
  
  
  rownames(meta) <- rownames(t_df)
  meta$Raw <- rownames(meta)
  
  
  
  
  t_df_meta <- merge(meta, t_df, by = "Raw")
  t_df_meta <- t_df_meta[order(t_df_meta[,2],t_df_meta[,3]),]
  
  

  return(t_df_meta)
  
}


# df <- ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_20ppm
# WhichIons <- c("y7", "y8", "y9")
aggregate_ions <- function(df, WhichIons){
  
  aggregate_average_ions <- aggregate(df[,which(colnames(df) == WhichIons)],
                                  list(df$Unique), mean)
  
  aggregate_stdev_ions <- aggregate(df[,which(colnames(df) == WhichIons)],
                                        list(df$Unique), sd)
  

  aggregate_sum_ions <- merge(aggregate_average_ions, aggregate_stdev_ions, by = "Group.1")
  
  colnames(aggregate_sum_ions) <- c("Unique", "y7_Average", "y8_Average", "y9_Average", "y7_Stdev", "y8_Stdev", "y9_Stdev")
  
  
  #aggregate_sum_ions$CV <- aggregate_sum_ions$stdev/aggregate_sum_ions$x*100
  
  
  aggregate_log2Average_ions <- log2(aggregate_average_ions[,-1])
  
  aggregate_log2Stdev_ions <- aggregate(df[,which(colnames(df) == WhichIons)],list(df$Unique), function(x) sd(log2(x)))
  rownames(aggregate_log2Stdev_ions) <- aggregate_log2Stdev_ions$Group.1
  aggregate_log2Stdev_ions <- aggregate_log2Stdev_ions[,-1]
  
  aggregate_log2 <- cbind(aggregate_log2Average_ions, aggregate_log2Stdev_ions)
  aggregate_log2$Unique <- rownames(aggregate_log2)
  
  aggregate_ions_all <- merge(aggregate_sum_ions, aggregate_log2, by = "Unique")
  colnames(aggregate_ions_all) <- c(colnames(aggregate_sum_ions), "Log2_Avg_y7", "Log2_Avg_y8",
                                "Log2_Avg_y9", "Log2_Stdev_y7", "Log2_Stdev_y8", "Log2_Stdev_y9")
  
  meta_aggregate <- df[which(df$Replicate == 1),1:6]
  
  aggregate_sum_ions_meta <- merge(meta_aggregate, aggregate_ions_all, by = "Unique")
  aggregate_sum_ions_meta <- aggregate_sum_ions_meta[,-c(2,5,6)]
  
  return(aggregate_sum_ions_meta)
}

#df <- ETDIGVTGGGQGK_y7y8y9_0_4_FAIMS_aggregate_20ppm 
long_aggregate <- function(df){
  
  rownames(df) <- df$Raw
  df_reduced <- df[,-c(1)] 
  long_y7y8y9_aggregate <- melt(df_reduced, id.vars = c("Unique", "Resolution", "MaxInjection","Replicate", "AGC"),
                                        variable.name = "Ion",
                                        value.name = "Intensity")
  
  to_split <- as.character(long_y7y8y9_aggregate$Ion)
  #Stat = sub(".*_","", to_split)
  #long_y7y8y9_aggregate$Ion <- sub("_.*","", to_split)
  #long_y7y8y9_aggregate$Stat <- Stat
  
  return(long_y7y8y9_aggregate)
  
}
```


```{r ETDIGVTGGGQGK_compiled_y7y8y9, echo=FALSE}
ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_20ppm <- df_y7y8y9_norm(ETDIGVTGGGQGK_CompiledFragments_0_6_FAIMS_20ppm)

ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_aggregate_20ppm <- aggregate_ions(ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_20ppm, c("y7", "y8", "y9"))
# long_y7y8y9_0_6_FAIMS_aggregate_20ppm <- long_aggregate(ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_20ppm)
# long_y7y8y9_0_4_FAIMS_aggregate_average <- long_y7y8y9_0_4_FAIMS_aggregate[ which(long_y7y8y9_0_4_FAIMS_aggregate$Stat == "Average"),]



E_y7_grob <- ggplot(ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= y7_Average, ymin = y7_Average-y7_Stdev, ymax = y7_Average+y7_Stdev, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=y7_Average),stat = "identity", alpha = 0.6, position = position_dodge())+
  scale_y_continuous(breaks = seq(0,1500000,500000), limit = c(0,1500000))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "ETDIGVTGGGQGK 0.6 Isolation Width with FAIMS" ,subtitle = "transition y7", y = "Intensity \n[abr. units]", x ="Resolution")

E_y8_grob <- ggplot(ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= y8_Average, ymin = y8_Average-y8_Stdev, ymax = y8_Average+y8_Stdev, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=y8_Average),stat = "identity", alpha = 0.6, position = position_dodge())+
  scale_y_continuous(breaks = seq(0,400000,100000), limit = c(0,400000))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "ETDIGVTGGGQGK 0.6 Isolation Width with FAIMS" ,subtitle = "transition y8", y = "Intensity \n[abr. units]", x ="Resolution")

E_y9_grob <- ggplot(ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= y9_Average, ymin = y9_Average-y9_Stdev, ymax = y9_Average+y9_Stdev, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=y9_Average),stat = "identity", alpha = 0.6, position = position_dodge())+
  scale_y_continuous(breaks = seq(0,2500000,500000), limit = c(0,2500000))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "ETDIGVTGGGQGK 0.6 Isolation Width with FAIMS" ,subtitle = "transition y9", y = "Intensity \n[abr. units]", x ="Resolution")
```

```{r ETDIGVTGGGQGK_compiled_y7y8y9, echo=FALSE}
AIEIVDQALDR_y7y8y9_0_6_FAIMS_20ppm <- df_y7y8y9_norm(AIEIVDQALDR_CompiledFragments_0_6_FAIMS_20ppm)

AIEIVDQALDR_y7y8y9_0_6_FAIMS_aggregate_20ppm <- aggregate_ions(AIEIVDQALDR_y7y8y9_0_6_FAIMS_20ppm, c("y7", "y8", "y9"))
# long_y7y8y9_0_6_FAIMS_aggregate_20ppm <- long_aggregate(ETDIGVTGGGQGK_y7y8y9_0_6_FAIMS_20ppm)
# long_y7y8y9_0_4_FAIMS_aggregate_average <- long_y7y8y9_0_4_FAIMS_aggregate[ which(long_y7y8y9_0_4_FAIMS_aggregate$Stat == "Average"),]



A_y7_grob <- ggplot(AIEIVDQALDR_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= y7_Average, ymin = y7_Average-y7_Stdev, ymax = y7_Average+y7_Stdev, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=y7_Average),stat = "identity", alpha = 0.6, position = position_dodge())+
  #scale_y_continuous(breaks = seq(0,36,2), limit = c(0,36))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "AIEIVDQALDR 0.6 Isolation Width with FAIMS" ,subtitle = "transition y7", y = "Intensity \n[abr. units]", x ="Resolution")

A_y8_grob <- ggplot(AIEIVDQALDR_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= y8_Average, ymin = y8_Average-y8_Stdev, ymax = y8_Average+y8_Stdev, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=y8_Average),stat = "identity", alpha = 0.6, position = position_dodge())+
  scale_y_continuous(breaks = seq(0,200000,50000), limit = c(0,200000))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "AIEIVDQALDR 0.6 Isolation Width with FAIMS" ,subtitle = "transition y8", y = "Intensity \n[abr. units]", x ="Resolution")

A_y9_grob <- ggplot(AIEIVDQALDR_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= y9_Average, ymin = y9_Average-y9_Stdev, ymax = y9_Average+y9_Stdev, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=y9_Average),stat = "identity", alpha = 0.6, position = position_dodge())+
  #scale_y_continuous(breaks = seq(0,36,2), limit = c(0,36))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "AIEIVDQALDR 0.6 Isolation Width with FAIMS" ,subtitle = "transition y9", y = "Intensity \n[abr. units]", x ="Resolution")

ggplot(AIEIVDQALDR_y7y8y9_0_6_FAIMS_aggregate_20ppm, aes(x=Resolution, y= Log2_Avg_y9, ymin = Log2_Avg_y9-Log2_Stdev_y9, ymax = Log2_Avg_y9+Log2_Stdev_y9, fill = factor(MaxInjection))) + 
  geom_bar(aes(y=Log2_Avg_y9),stat = "identity", alpha = 0.6, position = position_dodge())+
  scale_y_continuous(breaks = seq(0,20,5), limit = c(0,20))+
  geom_errorbar(width = 0.2, color= "#6D696F", position = position_dodge(width = 0.9)) +
  theme_light()+
  labs(title = "AIEIVDQALDR 0.6 Isolation Width with FAIMS" ,subtitle = "transition y9", y = "Intensity \n[abr. units]", x ="Resolution")

```

```{r individualIons_barplots, echo=FALSE}
E7grob <- ggplotGrob(E_y7_grob)
E8grob <- ggplotGrob(E_y8_grob)
E9grob <- ggplotGrob(E_y9_grob)


A7grob <- ggplotGrob(A_y7_grob)
A8grob <- ggplotGrob(A_y8_grob)
A9grob <- ggplotGrob(A_y9_grob)

pdf("F:/Projects/Proteomics/Zymomona/FAIMS/Figures/FromR/Parameter_Comparisono_HeatMaps/20ppm/ETDIGVTGGGQGK_AIEIVDQALDR_individual_yions_intensity.pdf", width = 20, height = 25,useDingbats = FALSE)
grid.arrange(E7grob, A7grob, E8grob, A8grob, E9grob,A9grob, ncol =2)
dev.off()

```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
